### ISSUE TITLE
[Question] Error when nuxt/pwa module is used

### ISSUE THREAD

**Issue by ikasianiuk** [nuxt-modules/partytown#141]
Hi and thanks for partytown integration for nuxt!

When I tried to use this module with nuxt2 project (that also has @nuxt/pwa module), sometimes I see 404 error saying that /~partytown/partytown-sandbox-sw.html file couldn't be found. I guess this is because they are both registered at the same root scop, so only one of them is working. 

I am a noob at service workers, so I was wandering, maybe you could help to find out how to have both of them? :)

**Comment by ikasianiuk** [comment]
Never mind, my issue was that I had `workbox: { enebled: false }` in `nuxt.config`. So a self-destroying service worker was registered and it also unregistered partytown service worker. Seems like changing setting to `workbox: false` fixed the issue

**Comment by danielroe** [comment]
No problem at all - glad it was resolved!
