### ISSUE TITLE
Communicate with web worker

### ISSUE THREAD

**Issue by stephenjason89** [nuxt-modules/partytown#156]
How do we communicate with the web worker like postMessage and stuff

**Comment by danielroe** [comment]
You can find the docs here: https://partytown.builder.io.

**Comment by stephenjason89** [comment]
Thanks @danielroe 
I might be wrong, but I have a 3 webworker scripts that i register like   

<img width="676" alt="image" src="https://user-images.githubusercontent.com/3810177/195528327-fc4068da-e147-4b88-964e-2bfbd0c2a46b.png">

from the worker itself i can call postMessage to send a message 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/3810177/195528766-adb01be3-22d1-4610-a855-ef3e27031b44.png">


I can then listen to the webworker's message like this
<img width="521" alt="image" src="https://user-images.githubusercontent.com/3810177/195528488-3b076bfe-1c20-48f0-9788-414f95c46177.png">


Is partytown able to handle this kind of stuff?
From the documentation above, I am not so certain. 

I am currently using https://www.npmjs.com/package/worker-plugin

Any clarifications on the matter is deeply appreciated.

**Comment by danielroe** [comment]
It's not like your other web workers in that you don't need to manually post messages. partytown automatically forwards events: https://partytown.builder.io/forwarding-events.

If it's not a Nuxt question, I would recommend engaging on https://github.com/BuilderIO/partytown instead.

**Comment by stephenjason89** [comment]
thank u @danielroe
