### ISSUE TITLE
Uses deprecated APIs

### ISSUE THREAD

**Issue by iD30** [nuxt-modules/partytown#219]
Google Page Insight score is 92/100 due to the following error `Event.path` is deprecated and will be removed. Please use `Event.composedPath()` instead.

I can see this has been fixed on Build.IO's Github (Link Below), but hasn't been implemented into the Nuxt version. 

https://github.com/BuilderIO/partytown/pull/328

Is there a possible work around for now , any and all help would be appreciated. 

Thank you.

**Comment by danielroe** [comment]
You should just need to run `npm upgrade` or equivalent as the fix is in 0.7.4 of the upstream library, which is within the version constraint of this module.
