### ISSUE TITLE
Release with partytown 0.10.0

### ISSUE THREAD

**Issue by krzkz94** [nuxt-modules/partytown#395]
Latest release for nuxt still has partytown 0.8.0, renovatebot recently merged a commit ([552a64e](https://github.com/nuxt-modules/partytown/commit/552a64e68f263f1ae1f8656b663705310ef155c9)) that bumps the partytown dependency to 0.10.0, can you do a release? 

Some functionality such as {preserveBehavior} released in 0.9.x would become available too :)

**Comment by danielroe** [comment]
Done ✅
